### ISSUE TITLE
Action hangs after shopify-cli install

### ISSUE THREAD

**Issue by jbreneman** [Shopify/shopify-cli-action#14]
Hello! We've been using this action to push changes to an app extension that our company builds. It's been working fine for the past few months, but out of the blue today it has stopped working for us. The last we used this action was mid-day on November 17th, and it was working then, so this started happening for us some time between then and now.

Anyway, the issue we're seeing is that once the action installs the necessary gems, it hangs with no further output. We left it going for about 15 minutes twice before canceling it, assuming something went wrong since normally it takes much less time. The last two lines we get in the logs are:
```
Successfully installed shopify-cli-2.32.0
12 gems installed
```
which I think means that it makes it though the cli install successfully at least, but either isn't continuing on or is getting stuck when trying to run the shopify-cli command.

We're running on `ubuntu-latest`, setting up ruby using `setup-ruby` @ version 2.7.5, and the command we're running is `shopify extension push`.

**Comment by jbreneman** [comment]
I ended up migrating to v3 of shopify-cli while trying to diagnose the issue and figured out the root cause of the issue--our CLI token had expired. I didn't set up the action initially so I didn't realize that the tokens expire and I'm guessing shopify-cli v2 either doesn't error in this case or the error isn't being passed to the action, so it wasn't obvious until I tried deploying with v3 with the same token.

**Comment by abhay-singh-au3** [comment]
Hi,

Do you know how to get the **_SHOPIFY_CLI_AUTH_TOKEN_**
Also how to upgrade to v3 of shopify-cli using shopify-cli-action

Thanks in advance!
